# API-запросы

# получение всех объявлений любым пользователем.
GET http://localhost:8000/api/advertisements/
Content-Type: application/json

###

# Получение конкретного объявления любым пользователем.
GET http://localhost:8000/api/advertisements/1/
Content-Type: application/json


###

# создание объявления. Пользователь admin.
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token e5e5ba06a5ce963b31a6086fef86a46ea140ad27

{
  "title": "Телевизор Хитачи",
  "description": "БУ, работает",
  "status": "OPEN"
}


###

# создание объявления. Пользователь sergei.
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token a8b25308daa0fd0c9d72a9b5fc6cf38689fcf875

{
  "title": "Картина маслом",
  "description": "автор Айвазовский",
  "status": "OPEN"
}


###

# попытка поменять текст объявления. Пользователь admin.
# текст меняется в открытых и закрытых объявлениях.
PATCH http://localhost:8000/api/advertisements/1/
Content-Type: application/json
Authorization: Token e5e5ba06a5ce963b31a6086fef86a46ea140ad27

{
  "title": "Люстра",
  "description": "Срочно"
}

###

# попытка поменять текст объявления. Пользователь sergei.
# текст меняется в открытых и закрытых объявлениях.
PATCH http://localhost:8000/api/advertisements/6/
Content-Type: application/json
Authorization: Token a8b25308daa0fd0c9d72a9b5fc6cf38689fcf875

{
  "title": "Канистра 10 литров",
  "description": "Для питьевой воды"
}

###

# попытка открыть/закрыть объявление. Пользователь admin.
PATCH http://localhost:8000/api/advertisements/53/
Content-Type: application/json
Authorization: Token e5e5ba06a5ce963b31a6086fef86a46ea140ad27

{
  "status": "CLOSED"
}

###

# попытка открыть/закрыть объявление. Пользователь sergei.
PATCH http://localhost:8000/api/advertisements/36/
Content-Type: application/json
Authorization: Token a8b25308daa0fd0c9d72a9b5fc6cf38689fcf875

{
  "status": "OPEN"
}

###

# удаление своего объявления. Пользователь admin.
DELETE http://localhost:8000/api/advertisements/5/
Content-Type: application/json
Authorization: Token e5e5ba06a5ce963b31a6086fef86a46ea140ad27

###

# удаление своего объявления. Пользователь sergei.
DELETE http://localhost:8000/api/advertisements/51/
Content-Type: application/json
Authorization: Token a8b25308daa0fd0c9d72a9b5fc6cf38689fcf875

###

# фильтрация объявлений по id создателя. Вывод всех объявлений пользователя. 
GET http://localhost:8000/api/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация объявлений по дате создания.
# вывод всех объявлений, созданных до выбранной даты. 
GET http://localhost:8000/api/advertisements/?created_at_before=2025-04-14
Content-Type: application/json

###

# фильтрация объявлений по статусу OPEN или CLOSED.
# вывод всех открытых или всех закрытых объявлений.
GET http://localhost:8000/api/advertisements/?status=CLOSED
Content-Type: application/json